name: .NET Ensure Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_all_proj:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore Nuget Packages
      run: dotnet restore Aiml.NET.sln
    - name: Build Solution
      run: dotnet build Aiml.NET.sln --no-restore
    - name: Test
      run: dotnet test Aiml.NET.sln --no-build --verbosity normal
